# Stage 1: Build
FROM python:3.11-slim AS build

WORKDIR /product-service
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Runtime
FROM python:3.11-slim

WORKDIR /product-service
COPY --from=build /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY . .

EXPOSE 8001
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

