# Build stage
FROM golang:1.21-alpine AS build
WORKDIR /user-service
COPY . .
RUN go mod init user-service
RUN go build -o main .

# Run stage
FROM alpine:latest
WORKDIR /root/
COPY --from=build /user-service/main .
EXPOSE 8080
CMD ["./main"]
