# Build stage (use latest secure Go version)
FROM golang:1.24.6-alpine AS build

WORKDIR /user-service
COPY . .
# For new Go projects, only use the following if go.mod does NOT already exist
RUN [ -f go.mod ] || go mod init user-service
RUN go build -o main .

# Run stage
FROM alpine:latest
WORKDIR /root/
COPY --from=build /user-service/main .
EXPOSE 8080
CMD ["./main"]